#!/bin/bash
# 加载一些环境变量
source /home/admin/dw/bin/common.sh


for json_name in $(ls /home/admin/dw/front_db)
do
  TABLE_NAME=${json_name//.json/}
  python ${SYSTEM_DATAX_HOME}/bin/datax.py \
-p "-DREADER_HOST=${FRONT_MYSQL_HOST} -DREADER_PORT=${FRONT_MYSQL_PORT} -DREADER_DATABASE_NAME=${FRONT_MYSQL_DATABASE_NAME} -DREADER_USERNAME=${FRONT_MYSQL_USERNAME} -DREADER_PASSWORD=${FRONT_MYSQL_PASSWORD} -DREADER_TABLE=${TABLE_NAME} -DWRITER_HOST=${BIG_DATA_OFFICE_MYSQL_HOST} -DWRITER_PORT=${BIG_DATA_OFFICE_MYSQL_PORT} -DWRITER_DATABASE_NAME=${BIG_DATA_OFFICE_MYSQL_DATABASE_NAME} -DWRITER_USERNAME=${BIG_DATA_OFFICE_MYSQL_USERNAME} -DWRITER_PASSWORD=${BIG_DATA_OFFICE_MYSQL_PASSWORD} -DWRITER_TABLE=${TABLE_NAME}" \
/home/admin/dw/front_db/${TABLE_NAME}.json
  echo ${TABLE_NAME}'完成了'
done